// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

let terms = [1, 2]

let findFibonacciEvenSum = arr => {

  for (let i = 2; arr[i-1]<=4000000; i++) {
    arr.push(arr[i-1] + arr[i-2])
  }

  let evenSum = arr.filter( y => y%2 === 0).reduce((acc, cv) => acc+cv)

  return evenSum
}

console.log(findFibonacciEvenSum(terms))
